#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Events\Dispatcher;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Zeropingheroes\LancacheAutofill\Commands\App\{
    InitialiseDatabase, InitialiseDownloadsDirectory
};
use Zeropingheroes\LancacheAutofill\Commands\Steam\{
    AuthoriseAccount, Dequeue, Initialise, QueueApp, QueuePopularApps, Requeue, SearchApps, ShowQueue, StartDownloading, UpdateAppList
};

// Load Composer's autoloader
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
}
else {
    require_once __DIR__.'/vendor/autoload.php';
}

// Load environment variables
$dotenv = new Dotenv(__DIR__);
$dotenv->load();
$dotenv->required(['DOWNLOADS_DIRECTORY', 'STEAMCMD_PATH']);

// Set up the console app
$app = new Application(new Container, new Dispatcher, '5.5');

// Set up the SQLite database connection
$capsule = new Capsule;
$capsule->addConnection([
    'driver' => 'sqlite',
    'database' => 'database.sqlite',
]);
$capsule->setAsGlobal();
$capsule->bootEloquent();

// Make commands available
$app->add(new InitialiseDatabase);
$app->add(new InitialiseDownloadsDirectory);

$app->add(new Initialise);
$app->add(new UpdateAppList);
$app->add(new SearchApps);
$app->add(new QueueApp);
$app->add(new QueuePopularApps);
$app->add(new ShowQueue);
$app->add(new StartDownloading);
$app->add(new AuthoriseAccount);
$app->add(new Dequeue);
$app->add(new Requeue);

// Run the console app
$app->run(new ArgvInput(), new ConsoleOutput());