#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Database\Capsule\Manager as Capsule;
use Dotenv\Dotenv;

use Zeropingheroes\LancacheAutofill\Console\Commands\Steam\{UpdateAppList, SearchApps, QueueApp, ShowQueue, StartDownloading};
use Zeropingheroes\LancacheAutofill\Console\Commands\{CreateDatabase, DeleteDownloads};

// Load Composer's autoloader
if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

// Load environment variables
$dotenv = new Dotenv(__DIR__);
$dotenv->load();
$dotenv->required(['DOWNLOAD_LOCATION', 'STEAMCMD', 'STEAM_USER']);

// Set up the console app
$app = new Application(new Container, new Dispatcher, '5.4');

// Set up the SQLite database connection
$capsule = new Capsule;
$capsule->addConnection([
    'driver'    => 'sqlite',
    'database'  => 'database.sqlite'
]);
$capsule->setAsGlobal();

// Make commands available
$app->add(new CreateDatabase);
$app->add(new DeleteDownloads);

$app->add(new UpdateAppList);
$app->add(new SearchApps);
$app->add(new QueueApp);
$app->add(new ShowQueue);
$app->add(new StartDownloading);

// Run the console app
$app->run();